### PR TITLE
Update dependencies to pass unit tests

### PR DESCRIPTION
**Pull request by coudot**
This is related to #6. I applied what @soisik has done for the LSC engine.

Please review and I will then merge.

### CODE REVIEW

**Comment by coudot** [comment]
I am currently working on travis to let it pass the tests

**Comment by coudot** [comment]
Hi @soisik, I got this error in unit test, but only with openjdk7:
` [java] Exception in thread "main" java.lang.ExceptionInInitializerError: A security class cannot be found in this JVM because of the following reason: sun.security.x509.CertAndKeyGen`

The OpenDJ server is well launched with oraclejdk7 and oraclejdk8. Do I need to add something to make it work with openjdk7?

**Comment by rouazana** [comment]
See https://bugster.forgerock.org/jira/browse/OPENDJ-2247
> Solution: Upgrade to 2.6.4 or later.

**Comment by coudot** [comment]
Indeed but 2.6.4 is not published in Forgerock mvn repository: http://maven.forgerock.org/repo/releases/org/forgerock/opendj/opendj-server/

I wonder why it works in lsc-core and not in this plugin.

**Comment by coudot** [comment]
Ok, why it fails it's because I need to install ldap-utils package, which is not in [Travis apt package whitelist](https://github.com/travis-ci/apt-package-whitelist) (see https://docs.travis-ci.com/user/installing-dependencies).

So we switched to a debian box which provides OpenJDK 1.7.0_121. In the default Travis container we have OpenJDK 1.7.0_75.

So our builds fail for OpenJDK 7 version after this commit http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/rev/2e88b2895a8c

As @rouazana said, the solution is to use OpenDJ >= 2.6.4, but it is not possible as minor versions are not published by ForgeRock (2.6.2 was an exception needed for OpenAM). Time to switch to real free software (ApacheDS) ? 

I will remove openjdk7 from Travis tests, as we still have running tests with OracleJDK 7 and Oracle JDK 8.

**Pull request merged**
